/**
 * VolunteerHub OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Donation { 
    DonationUid?: string;
    UserUid?: string;
    Amount?: number;
    DateTime?: string;
    SyncId?: string;
    SyncHash?: string;
}

