/**
 * VolunteerHub OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserGroupRegistration } from './userGroupRegistration';


export interface Event { 
    EventUid?: string;
    EndTime?: string;
    EventGroupUid?: string;
    Location?: string;
    LongDescription?: string;
    Name?: string;
    RaisersEdgeJobId?: string;
    ShortDescription?: string;
    StartTime?: string;
    SlotLimit?: number;
    Version?: number;
    UserGroupRegistrations?: Array<UserGroupRegistration>;
}

