/**
 * VolunteerHub OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormQuestion } from './formQuestion';


export interface Form { 
    Name?: string;
    FormQuestions?: Array<FormQuestion>;
}

