/**
 * VolunteerHub OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FormQuestion { 
    FormQuestionUid?: string;
    Editability?: FormQuestion.EditabilityEnum;
    FormQuestionType?: FormQuestion.FormQuestionTypeEnum;
    Name?: string;
    Ordinal?: number;
    Prompt?: string;
    Required?: boolean;
    SubPrompt?: string;
    Visibility?: FormQuestion.VisibilityEnum;
    Tokens?: Array<FormQuestion.TokensEnum>;
}
export namespace FormQuestion {
    export type EditabilityEnum = 'AdministratorsAndUsers' | 'AdministratorsOnly' | 'System';
    export const EditabilityEnum = {
        AdministratorsAndUsers: 'AdministratorsAndUsers' as EditabilityEnum,
        AdministratorsOnly: 'AdministratorsOnly' as EditabilityEnum,
        System: 'System' as EditabilityEnum
    };
    export type FormQuestionTypeEnum = 'Address' | 'Boolean' | 'Date' | 'EmailAddress' | 'Header' | 'Integer' | 'List' | 'Name' | 'PhoneNumber' | 'Photos' | 'Skill' | 'String';
    export const FormQuestionTypeEnum = {
        Address: 'Address' as FormQuestionTypeEnum,
        Boolean: 'Boolean' as FormQuestionTypeEnum,
        Date: 'Date' as FormQuestionTypeEnum,
        EmailAddress: 'EmailAddress' as FormQuestionTypeEnum,
        Header: 'Header' as FormQuestionTypeEnum,
        Integer: 'Integer' as FormQuestionTypeEnum,
        List: 'List' as FormQuestionTypeEnum,
        Name: 'Name' as FormQuestionTypeEnum,
        PhoneNumber: 'PhoneNumber' as FormQuestionTypeEnum,
        Photos: 'Photos' as FormQuestionTypeEnum,
        Skill: 'Skill' as FormQuestionTypeEnum,
        String: 'String' as FormQuestionTypeEnum
    };
    export type VisibilityEnum = 'AdministratorsAndUsers' | 'AdministratorsOnly';
    export const VisibilityEnum = {
        AdministratorsAndUsers: 'AdministratorsAndUsers' as VisibilityEnum,
        AdministratorsOnly: 'AdministratorsOnly' as VisibilityEnum
    };
    export type TokensEnum = 'UserEmailAddress' | 'UserAddress' | 'UserName' | 'UserHomePhone' | 'UserWorkPhone' | 'UserMobilePhone' | 'UserPager' | 'UserFax' | 'UserGender' | 'UserBirthday' | 'EmailAllowed' | 'SmsAllowed' | 'EmergencyContactName' | 'EmergencyContactPhone' | 'UserCountry' | 'DonorPerfectId' | 'Irs13206VolunteerPosition' | 'Irs13206VolunteerCertification' | 'PinCode' | 'BackgroundScreeningReportUrl' | 'DonationName' | 'DonationAddress' | 'UserProfilePhoto';
    export const TokensEnum = {
        UserEmailAddress: 'UserEmailAddress' as TokensEnum,
        UserAddress: 'UserAddress' as TokensEnum,
        UserName: 'UserName' as TokensEnum,
        UserHomePhone: 'UserHomePhone' as TokensEnum,
        UserWorkPhone: 'UserWorkPhone' as TokensEnum,
        UserMobilePhone: 'UserMobilePhone' as TokensEnum,
        UserPager: 'UserPager' as TokensEnum,
        UserFax: 'UserFax' as TokensEnum,
        UserGender: 'UserGender' as TokensEnum,
        UserBirthday: 'UserBirthday' as TokensEnum,
        EmailAllowed: 'EmailAllowed' as TokensEnum,
        SmsAllowed: 'SmsAllowed' as TokensEnum,
        EmergencyContactName: 'EmergencyContactName' as TokensEnum,
        EmergencyContactPhone: 'EmergencyContactPhone' as TokensEnum,
        UserCountry: 'UserCountry' as TokensEnum,
        DonorPerfectId: 'DonorPerfectId' as TokensEnum,
        Irs13206VolunteerPosition: 'Irs13206VolunteerPosition' as TokensEnum,
        Irs13206VolunteerCertification: 'Irs13206VolunteerCertification' as TokensEnum,
        PinCode: 'PinCode' as TokensEnum,
        BackgroundScreeningReportUrl: 'BackgroundScreeningReportUrl' as TokensEnum,
        DonationName: 'DonationName' as TokensEnum,
        DonationAddress: 'DonationAddress' as TokensEnum,
        UserProfilePhoto: 'UserProfilePhoto' as TokensEnum
    };
}


