/**
 * VolunteerHub OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Form } from './form';
import { RaisersEdgeConfiguration } from './raisersEdgeConfiguration';


export interface Organization { 
    ContactUserUid?: string;
    Name?: string;
    Url?: string;
    Forms?: Array<Form>;
    RaisersEdgeConfiguration?: RaisersEdgeConfiguration;
}

