/**
 * VolunteerHub OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RaisersEdge { 
    Id?: string;
    AddressHash?: string;
    EmailHash?: string;
    HomePhoneHash?: string;
    MobilePhoneHash?: string;
    NameHash?: string;
    WorkPhoneHash?: string;
}

