/**
 * VolunteerHub OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RaisersEdgeJob } from './raisersEdgeJob';


export interface RaisersEdgeConfiguration { 
    PrimaryAddresseeId?: number;
    PrimarySalutationId?: number;
    WorkPhoneKey?: string;
    HomePhoneKey?: string;
    EmailPhoneKey?: string;
    MobilePhoneKey?: string;
    UsePreferredAddress?: boolean;
    AddressKey?: string;
    SetAsPreferredAddress?: boolean;
    VolunteerHubConstituentCode?: string;
    VolunteerConstituentCode?: string;
    IndividualConstituentCode?: string;
    DefaultMaritalStatus?: string;
    SyncUserRegistrationsWithoutHours?: boolean;
    IgnoreDuplicateAddresses?: boolean;
    DuplicateAddressKey?: string;
    FundName?: string;
    AppealName?: string;
    Enabled?: boolean;
    Jobs?: Array<RaisersEdgeJob>;
    DeleteRelationships?: boolean;
}

