/**
 * VolunteerHub OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRegistration } from './userRegistration';


export interface UserGroupRegistration { 
    AnonymousHours?: number;
    AnonymousSlotsUsed?: number;
    Deleted?: boolean;
    SlotsReserved?: number;
    UserGroupUid?: string;
    UserRegistrations?: Array<UserRegistration>;
}

