/**
 * VolunteerHub OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRegistrationRaisersEdge } from './userRegistrationRaisersEdge';


export interface UserRegistration { 
    Deleted?: boolean;
    Hours?: number;
    RaisersEdge?: UserRegistrationRaisersEdge;
    RegistrationDate?: string;
    UserUid?: string;
    AnonymousSlotsUsed?: number;
    Waitlisted?: boolean;
}

