/**
 * VolunteerHub OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RaisersEdgeOrganization } from './raisersEdgeOrganization';


export interface UserGroup { 
    UserGroupUid?: string;
    Description?: string;
    Name?: string;
    ParentUserGroupUid?: string;
    RaisersEdgeOrganization?: RaisersEdgeOrganization;
    RaisersEdgeRelationshipDescription?: string;
    Lineage?: string;
}

