/**
 * VolunteerHub OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RaisersEdge } from './raisersEdge';
import { FormAnswer } from './formAnswer';


export interface UserV2 { 
    UserUid?: string;
    LastUpdate?: string;
    RaisersEdge?: RaisersEdge;
    FormAnswers?: Array<FormAnswer>;
    UserGroupMemberships?: Array<string>;
    Username?: string;
    Version?: number;
    Created?: string;
    EmailAllowed?: boolean;
}

